In [1]:
import os,json
from tqdm.notebook import tqdm

import pandas as pd

In [4]:
path = '../../data/labelled/'

data = []

for subdir in os.listdir(path):
    if os.path.isdir(os.path.join(path, subdir)):
        print(subdir)
        data.append(pd.read_json(os.path.join(path, subdir,f'{subdir}.json'),orient='records'))

synopses
scraped
studies

/tmp/ipykernel_2357542/1324910233.py:8: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  data.append(pd.read_json(os.path.join(path, subdir,f'{subdir}.json'),orient='records'))
/tmp/ipykernel_2357542/1324910233.py:8: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  data.append(pd.read_json(os.path.join(path, subdir,f'{subdir}.json'),orient='records'))
/tmp/ipykernel_2357542/1324910233.py:8: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  data.append(pd.read_json(os.path.join(path, subdir,f'{subdir}.json'),orient='records'))

In [12]:

data = pd.concat(data)

data.head()

,reference type,author,year,title,series editor,series/book title,place published,institution,publisher,date,doi,relevance,multiclasses,abstract,url,text,class,report number,folder
0,CE Study,NaN,NaN,Subtidal Benthic Invertebrate,NaN,NaN,None,Conservation Evidence Team,Conservation Evidence,NaT,NaN,relevant,[Marine Invertebrates],NaN,https://www.conservationevidence.com/synopsis/...,1 \n \n \n2 \n \n \nSubtidal Benthic Invertebr...,NaN,NaN,NaN
1,CE Study,NaN,NaN,Invasive Freshwater Species,NaN,NaN,None,Conservation Evidence Team,Conservation Evidence,NaT,NaN,relevant,"[Fish, Rivers and Lakes, Invasive]",NaN,https://www.conservationevidence.com/synopsis/...,\n \n \n Control of freshwater \n invasi...,NaN,NaN,NaN
2,CE Study,NaN,NaN,Grassland,NaN,NaN,None,Conservation Evidence Team,Conservation Evidence,NaT,NaN,relevant,[Grassland],NaN,https://www.conservationevidence.com/synopsis/...,1 \n \nGrassland Conservation \n2 \n \nGrassla...,NaN,NaN,NaN
3,CE Study,NaN,NaN,Primate,NaN,NaN,None,Conservation Evidence Team,Conservation Evidence,NaT,NaN,relevant,[Mammals],NaN,https://www.conservationevidence.com/synopsis/...,\n \n \nii \n \n \n \n \n \n \n \nPrimate Co...,NaN,NaN,NaN
4,CE Study,NaN,NaN,Terrestrial Mammal,NaN,NaN,None,Conservation Evidence Team,Conservation Evidence,NaT,NaN,relevant,[Mammals],NaN,https://www.conservationevidence.com/synopsis/...,CONSERVATION EVIDENCE SERIES SYNOPSES\nTerrest...,NaN,NaN,NaN

In [13]:
# filter down and drop unknown classes
write_data = data[['url','text','relevance','multiclasses']].dropna(subset=['multiclasses'])
write_data.head()

,url,text,relevance,multiclasses
0,https://www.conservationevidence.com/synopsis/...,1 \n \n \n2 \n \n \nSubtidal Benthic Invertebr...,relevant,[Marine Invertebrates]
1,https://www.conservationevidence.com/synopsis/...,\n \n \n Control of freshwater \n invasi...,relevant,"[Fish, Rivers and Lakes, Invasive]"
2,https://www.conservationevidence.com/synopsis/...,1 \n \nGrassland Conservation \n2 \n \nGrassla...,relevant,[Grassland]
3,https://www.conservationevidence.com/synopsis/...,\n \n \nii \n \n \n \n \n \n \n \nPrimate Co...,relevant,[Mammals]
4,https://www.conservationevidence.com/synopsis/...,CONSERVATION EVIDENCE SERIES SYNOPSES\nTerrest...,relevant,[Mammals]

In [14]:
write_data.to_json('../../data/labelled/relevant.json',orient='records')

In [15]:
def merge_data():
    relevant = pd.read_json('../../data/labelled/relevant.json',orient='records')
    irrelevant = pd.read_json('../../data/labelled/irrelevant.json',orient='records')
    data = pd.concat([relevant,irrelevant])
    return data

merged_data = merge_data()
print(merged_data.info())
merged_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 20901 entries, 0 to 10687
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           20901 non-null  object
 1   text          20901 non-null  object
 2   relevance     20901 non-null  object
 3   multiclasses  20901 non-null  object
dtypes: object(4)
memory usage: 816.4+ KB
None

,url,text,relevance,multiclasses
0,https://www.conservationevidence.com/synopsis/...,1 \n \n \n2 \n \n \nSubtidal Benthic Invertebr...,relevant,[Marine Invertebrates]
1,https://www.conservationevidence.com/synopsis/...,\n \n \n Control of freshwater \n invasi...,relevant,"[Fish, Rivers and Lakes, Invasive]"
2,https://www.conservationevidence.com/synopsis/...,1 \n \nGrassland Conservation \n2 \n \nGrassla...,relevant,[Grassland]
3,https://www.conservationevidence.com/synopsis/...,\n \n \nii \n \n \n \n \n \n \n \nPrimate Co...,relevant,[Mammals]
4,https://www.conservationevidence.com/synopsis/...,CONSERVATION EVIDENCE SERIES SYNOPSES\nTerrest...,relevant,[Mammals]

In [16]:

merged_data.to_json('../../data/labelled/data.json',orient='records')